### ISSUE TITLE
動画をcv2.VideoCaptureで取り込む

### ISSUE THREAD

**Issue by 0xShin0221** [shinri-sone/traffic_counter_RaspberryPi#1]
## 実装内容
- [x] mp4ファイルを送る
- [x] OpenCVで動画を読み込み
- [x] gitで編集したものをコミット・プッシュする

## 現在
下記ラインでWebカメラを直接配信している
https://github.com/shinri-sone/traffic_counter_RaspberryPi/blob/4180562adb120c6e7471f8b0c5f799a9b9375dec/object_detection/detect_opencv.py#L113

## 実装の参考
https://note.nkmk.me/python-opencv-videocapture-file-camera/

**Comment by shinri-sone** [comment]
20200415成功
